name: Scan Published Assets

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            LaF_Setup_Linux_x86_64.AppImage
            LaF_Setup_macOS_x64.dmg
            LaF_Setup_Windows_x64.exe