name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install g++-multilib

      - name: Config for msvc
        if: matrix.os == 'windows-latest'
        run: npm config set msvs_version 2019

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install dependencies
        run: npm install --loglevel silly

      - name: Build and Release
        run: npm run dist
        env: 
          GH_TOKEN: ${{ secrets.github_token }}
